build.gradle
src/main/kotlin/mu/internal/KLoggerFactory.kt
src/main/kotlin/mu/internal/KLoggerNameResolver.kt
src/test/kotlin/mu/internal/KLoggerNameResolverTest.kt

added a fix to replace kotlin reflection with java reflection

---

src/main/kotlin/mu/KotlinLogging.kt
src/main/kotlin/mu/internal/KLoggerFactory.kt
src/main/kotlin/mu/internal/KLoggerNameResolver.kt
src/test/kotlin/mu/KotlinLoggingTest.kt

add KotlinLogging to support class level logging - a suggestion for issue #12

---

README.md

apply latest version to maven/gradle

---

build.gradle.kts
versions.gradle.kts

Signed-off-by: Piyush Mor <piyush.mor@gmail.com>
solves #97

Upgrade slf4j and kotlin platform

---

build.gradle.kts
src/jvmTest/kotlin/mu/LoggingTest.kt

This reverts commit e0fff5ba until #130 is resolved

Revert "Upgrade to Kotlin 1.4.0 (#127)"

---

build.gradle.kts
settings.gradle.kts
src/jvmTest/kotlin/mu/LoggingTest.kt

Apply commit c722ca8a to 1.x branch
without breaking compatibility.

upgrade kotlin to 1.4

---

.travis.yml
build.gradle.kts

issue #177
using signing and publish plugin:
https://github.com/gradle-nexus/publish-plugin

publish to maven central directly

---

src/jvmMain/kotlin/mu/internal/KLoggerNameResolver.kt
src/jvmTest/kotlin/mu/internal/KLoggerNameResolverTest.kt

Fix for #182 that changes a reflection method.

Fix #182 - change a reflection method so that it works on private fields

---

README.md

just a fix of the version in README

update kotlin jvm version to 2.0.10

---

build.gradle.kts

Notable updates are a revised UI as well as the `expect` and `actual` keywords are now added to signatures.

Upgraded Dokka to 1.6.0

---

build.gradle.kts

reference:
https://github.com/ajalt/clikt/pull/295

add "Automatic-Module-Name" for #223

---

build.gradle.kts

set jvmTarget back to 8

---

src/commonMain/kotlin/io/github/oshai/KLogger.kt
src/commonMain/kotlin/io/github/oshai/KotlinLogging.kt
src/commonMain/kotlin/io/github/oshai/Level.kt
src/jsMain/kotlin/io/github/oshai/KLogger.kt
src/jsMain/kotlin/io/github/oshai/internal/KLoggerJS.kt
src/jvmMain/kotlin/io/github/oshai/KLogger.kt
src/jvmMain/kotlin/io/github/oshai/KLogging.kt
src/nativeMain/kotlin/io/github/oshai/DefaultMessageFormatter.kt
src/nativeMain/kotlin/io/github/oshai/Formatter.kt
src/nativeMain/kotlin/io/github/oshai/KLogger.kt
src/nativeMain/kotlin/io/github/oshai/KotlinLoggingLevel.kt
src/nativeMain/kotlin/io/github/oshai/internal/KLoggerLinux.kt

add missing klogger common methods

---

build.gradle.kts
src/jvmMain/kotlin/io/github/oshai/coroutines/KotlinLoggingAsyncMDC.kt
src/jvmTest/kotlin/io/github/oshai/coroutines/KotlinLoggingAsyncMDCTest.kt
versions.gradle.kts

Issue #165
Based on https://github.com/Kotlin/kotlinx.coroutines/pull/3092
coroutines / slf4j dependency is compile only (users needs to add it)

add withLoggingContextAsync

---

src/jsMain/kotlin/io/github/oshai/KotlinLogging.kt
src/jsTest/kotlin/io/github/oshai/SimpleJsTest.kt

used by private val logger by KotlinLogging.logger()

add js delegate

---

.github/workflows/ci.yml

This will help to validate changes like #238 
See https://github.com/gradle/wrapper-validation-action and https://docs.gradle.org/current/userguide/gradle_wrapper.html#wrapper_checksum_verification

ci: add Gradle wrapper validation

---

gradle/wrapper/gradle-wrapper.properties

build: bump gradle wrapper to 7.6.1

---

.github/dependabot.yml

Fixes a small indentation issue introduced with #291 
See https://github.com/oshai/kotlin-logging/runs/12343127047
Tested here https://github.com/yeikel/kotlin-logging/runs/12349290174
See results here https://github.com/yeikel/kotlin-logging/pulls

chore(dependabot): fix indentation

---

src/nativeMain/kotlin/io/github/oshai/kotlinlogging/ConsoleOutputAppender.kt

Protect from string format attack:
https://owasp.org/www-community/attacks/Format_string_attack

fix - protect from uncontrolled format string

---

gradle.properties

Removing setting in gradle.properties that should theoretically no longer be needed
Fixes #418

Remove Gradle workaround

---

build.gradle.kts

Added Android native targets

---

README.md

Just update the version of README.md to the latest one

Update version of README.md to 7.0.0
