- .gitignore
- src/main/kotlin/mu/KLogger.kt
- src/main/kotlin/mu/internal/LocationAwareKLogger.kt
- src/main/kotlin/mu/internal/MessageInvoker.kt
- src/test/kotlin/mu/LoggingTest.kt
Sometimes classes have incorrect toString implementation, which raises exception.
To avoid this, logger should cautch and inform developer.
Such behavior is used in the many popular loggers, we should reuse it too
> Suppress exceptions from toString methods

- kotlin-logging-jvm/src/main/kotlin/mu/KLogger.kt
- kotlin-logging-jvm/src/main/kotlin/mu/internal/LocationAwareKLogger.kt
- kotlin-logging-jvm/src/test/kotlin/mu/LoggingTest.kt
This change simply accepts `Throwable?` instead of `Throwable`. Slf4j treats ignores null throwables.
> Accept nullable Throwables (#38)

- kotlin-logging-js/src/main/kotlin/mu/ConsoleOutputPipes.kt
- kotlin-logging-js/src/main/kotlin/mu/DefaultMessageFormatter.kt
- kotlin-logging-js/src/main/kotlin/mu/KotlinLoggingLevel.kt
- kotlin-logging-js/src/main/kotlin/mu/MessageFormatter.kt
- kotlin-logging-js/src/main/kotlin/mu/OutputPipes.kt
- kotlin-logging-js/src/main/kotlin/mu/internal/KLoggerJS.kt
So mostly this is freehand refactoring (it'd be nice to add a test suite to the JS side here). But additionally, there are two new JS configurable variables at the root, such that someone using the library can modify or replace the message formatting.
I quick put this together because I was adding some logging to an app I've been converting to Kotlin-Js, and couldn't quite get it to produce JSON log lines rather than traditional ones. 🤷🏻‍♂️
> Javascript - Extracting Message Formatter interface

- kotlin-logging-common/src/main/kotlin/mu/KLogger.kt
- kotlin-logging-js/src/main/kotlin/mu/KLogger.kt
- kotlin-logging-js/src/main/kotlin/mu/internal/KLoggerJS.kt
- kotlin-logging-jvm/src/main/kotlin/mu/KLogger.kt
- kotlin-logging-jvm/src/main/kotlin/mu/internal/LocationAwareKLogger.kt
- kotlin-logging-jvm/src/main/kotlin/mu/internal/LocationIgnorantKLogger.kt
- kotlin-logging-jvm/src/test/kotlin/mu/ClassWithLoggingForLocationTesting.kt
- kotlin-logging-jvm/src/test/kotlin/mu/LoggingWithLocationTest.kt
This PR only adds the entry, exit, throwing and catching methods to the existing logger.
The location-aware logger will add method names etc.
The LocationIgnorant and JS implementations are similar.
We may want to add markers.
> added support for same functionality as slf4j-ext.

- README.md
This PR fixes typographical errors in the README.md, including:
- Capitalization
- Proper nouns
- Missing words
- Inconsistent kotlin-logging branding
> Update README.md Content & Typographical Errors

- src/commonMain/kotlin/mu/KLogger.kt
- src/jsMain/kotlin/mu/KLogger.kt
- src/jsMain/kotlin/mu/internal/KLoggerJS.kt
- src/jvmMain/kotlin/mu/KLogger.kt
- src/jvmMain/kotlin/mu/internal/LocationAwareKLogger.kt
- src/jvmMain/kotlin/mu/internal/LocationIgnorantKLogger.kt
- src/jvmTest/kotlin/mu/ClassWithLoggingForLocationTesting.kt
- src/jvmTest/kotlin/mu/LoggingWithLocationTest.kt
The type for entry is `vararg Any` and should be `vararg Any?` 
The name for exit was `retval` and `result` will  be better.
> Provide for nullable in entry and rename exit argument

- build.gradle.kts
- src/commonMain/kotlin/mu/KotlinLogging.kt
- src/jsMain/kotlin/mu/KotlinLogging.kt
- src/jvmMain/kotlin/mu/KLogger.kt
- src/jvmMain/kotlin/mu/KLogging.kt
- src/jvmMain/kotlin/mu/KotlinLogging.kt
- src/jvmMain/kotlin/mu/KotlinLoggingMDC.kt
Signed-off-by: Piyush Mor <piyush.mor@gmail.com>
solves #82
> use Dokka for javadocs #82

- .travis.yml
- build.gradle.kts
- gradle.properties
Adds builds for the brower and NodeJS.
Enables JS-IR (with `both` mode).
Should fix #126.
> Support JS-IR backend

- .travis.yml
Since the addition of release builds,
travis is trying to deploy PR that are coming from
a master branch because of the 'branch = master' condition.
To overcome this added a special env variable RELEASE_BRANCH that is set only on the release branches and checking it for release.
> don't try to release on non release branches

- README.md
Setup with this library was super easy except that it wasn't obvious from the main README what the import line for KotlinLogging should be. Adding it in the getting started example would have been handy for me, maybe it'll help others?
> Add `import mu.KotlinLogging;` statement to getting started in README

- README.md
Declaring dependencies as `compile` is no longer a best practice in Gradle. [See here](https://docs.gradle.org/current/userguide/java_library_plugin.html).
Instead, they should be declared as `implementation`.
> Declaring example dependencies as implementation

- src/commonMain/kotlin/mu/internal/MessageInvoker.kt
- src/jsMain/kotlin/mu/internal/ErrorMessageProducer.kt
- src/jvmMain/kotlin/mu/internal/ErrorMessageProducer.kt
- src/jvmTest/kotlin/mu/internal/MessageInvokerJavaTest.kt
- src/nativeMain/kotlin/mu/internal/ErrorMessageProducer.kt
in case system property is defined: kotlin-logging.throwOnMessageError
> Fix #160 - throw error instead of show in log

- src/jvmMain/kotlin/mu/KotlinLoggingMDC.kt
- src/jvmTest/kotlin/mu/KotlinLoggingMDCTest.kt
`withLoggingContext` now accepts nullable values that won't be written
to the `MDC` (and thus also don't overwrite existing values).
This might be useful if some values are not guaranteed to exist, but you
want them in the `MDC` if possible.
Issue: #172
> Support nullables in withLoggingContext

- build.gradle.kts
Kotlin 1.5 is out, but kotlin-logging still being on 1.4 causes dependency conflicts in my project. With this change, I bump the Kotlin version to 1.5.
https://blog.jetbrains.com/kotlin/2021/05/kotlin-1-5-0-released/
> Bump to Kotlin 1.5

- build.gradle.kts
Issue https://github.com/MicroUtils/kotlin-logging/issues/188
Comments for solutions:
1. I removed all `apply` because plugins are already applied in `plugins` sections
2. There are 2 Jar tasks in the gradle: 
- `org.gradle.jvm.tasks.Jar`
- `org.gradle.api.tasks.bundling.Jar` is subtype of `org.gradle.jvm.tasks.Jar`.
In build.gradle.kts by default using `org.gradle.api.tasks.bundling.Jar`, but Kotlin multiplatform register `sourcesJar` task with type `org.gradle.jvm.tasks.Jar`. 
So I added `import org.gradle.jvm.tasks.Jar` to add a license to all jar tasks.
> added the license to all jar files

- .travis.yml
osx is now built, but not released. trying to split travis jobs for build+release to also release it.
Part of issue #166
> split travis targets to linux and osx jobs

- versions.gradle.kts
There is a critical vulnerability in Log4j, more information here:
https://www.lunasec.io/docs/blog/log4j-zero-day/
> Fix critical vulnerability in log4j

- src/jvmMain/kotlin/mu/KLogger.kt
- src/jvmMain/kotlin/mu/KotlinLoggingMDC.kt
- src/jvmMain/kotlin/mu/internal/KLoggerNameResolver.kt
- src/jvmMain/kotlin/mu/internal/LocationAwareKLogger.kt
- src/jvmMain/kotlin/mu/internal/LocationIgnorantKLogger.kt
- src/jvmTest/kotlin/mu/KotlinLoggingMDCTest.kt
Removed "exception as control flow" in KLoggerNameResolver.unwrapCompanionClass(); Consolidated MDC cleanup code in KotlinLoggingMDC
> Addressing points raised in detektJvmMain task

- versions.gradle.kts
For resolve problem of Security Vulnerabilities (CVE-2021-45046)
https://logging.apache.org/log4j/2.x/security.html
> Upgraded log4j from 2.15.0 to 2.16.0 (CVE-2021-45046)

- build.gradle.kts
- src/darwinMain/kotlin/mu/KotlinLoggingConfiguration.kt
- src/darwinMain/kotlin/mu/OSLogAppender.kt
- src/darwinMain/kotlin/mu/OSLogSubsystemAppender.kt
- src/linuxMain/kotlin/mu/KotlinLoggingConfiguration.kt
- src/nativeMain/kotlin/mu/Appender.kt
- src/nativeMain/kotlin/mu/ConsoleOutputAppender.kt
- src/nativeMain/kotlin/mu/DefaultMessageFormatter.kt
- src/nativeMain/kotlin/mu/Formatter.kt
- src/nativeMain/kotlin/mu/KMarkerFactory.kt
- src/nativeMain/kotlin/mu/KotlinLoggingConfiguration.kt
- src/nativeMain/kotlin/mu/internal/KLoggerLinux.kt
- src/nativeMain/kotlin/mu/internal/MarkerNative.kt
Apple platforms (macOS, iOS, watchOS, tvOS) have a [unified logging system](https://developer.apple.com/documentation/os/logging?language=objc) called `os_log`. I implemented support for `os_log` and made it the default on Apple platforms. This is similar to how `slf4j-android` implements `slf4j-api` to write to the Android system log.
I kept the console output appender still available on Apple platforms because it might still be desirable to use it in, for example, a command line tool.
`os_log` has two key concepts – a subsystem and a category. A subsystem is intended to be constant for an entire project (i.e. the reverse DNS notation for the project) and the category is supposed to change based on the component. Neither are usually part of the log message string itself, but rather used …
> Add support for os_log on Apple platforms

- versions.gradle.kts
Release notes: https://logging.apache.org/log4j/2.x/changes-report.html#a2.18.0
> build(deps): bump log4j from 2.17.1 to 2.18.0

- build.gradle.kts
- versions.gradle.kts
Bump log4j from 2.18.0 to 2.19.0
- Bumps log4j from 2.18.0 to 2.19.0
- Bumps slf4j from 1.7.32 to 2.0.1
- Migrates to `log4j-slf4j2`. See https://logging.apache.org/log4j/2.x/log4j-slf4j-impl/index.html
Release notes: 
log4j : https://logging.apache.org/log4j/2.x/changes-report.html#a2.19.0
slf4j  : https://www.slf4j.org/faq.html#changesInVersion200
> build(deps): bump log4j from 2.18.0 to 2.19.0

- build.gradle.kts
- versions.gradle.kts
The release [mockito-all](https://search.maven.org/artifact/org.mockito/mockito-all) is [1.10.19](https://search.maven.org/artifact/org.mockito/mockito-all/1.10.19/jar) and that was released in 2014. Newer versions of Mockito don't release mockito-all anymore.
> build(test-dep): Migrate to mockito-core

- build.gradle.kts
See https://github.com/JetBrains/kotlin/releases/tag/v1.7.21
> build(deps): bump kotlin multiplatform from 1.7.20 to 1.7.21

- versions.gradle.kts
Release notes https://logging.apache.org/log4j/2.x/release-notes/2.20.0.html
> build(deps): bump log4j2 from 2.19.0 to 2.20.0

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- Adopt is no longer maintained
See https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#adopt
> NOTE: Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from adopt to temurin to keep receiving software and security updates. See more details in the [Good-bye AdoptOpenJDK post](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/).
- Temurin instances are cached by default on the GitHub Hosted Runners so there is no need to download them every time
See https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#hosted-tool-cache
> ci: use temurin

- src/androidMain/kotlin/io/github/oshai/KLogger.kt
- src/androidMain/kotlin/io/github/oshai/internal/KLoggerAndroid.kt
- src/commonMain/kotlin/io/github/oshai/KLogger.kt
- src/commonMain/kotlin/io/github/oshai/Level.kt
- src/jsMain/kotlin/io/github/oshai/internal/KLoggerJS.kt
- src/jsTest/kotlin/io/github/oshai/SimpleJsTest.kt
- src/jvmMain/kotlin/io/github/oshai/KLogger.kt
- src/jvmMain/kotlin/io/github/oshai/jul/internal/JulLoggerWrapper.kt
- src/jvmMain/kotlin/io/github/oshai/slf4j/internal/Slf4jLoggerWrapper.kt
- src/nativeMain/kotlin/io/github/oshai/internal/KLoggerNative.kt
- src/nativeTest/kotlin/io/github/oshai/SimpleNativeTest.kt
Fixes #310.
I added the minimum amount of code to make this work, together with a test for JS and native.
It might make sense to add an `isOff` property to `KLogger` (which could probably even be implemented in common code as `!isErrorEnabled`), let me know what you think.
> Allow turning off logging with `Level.OFF`

- src/javaMain/kotlin/io/github/oshai/kotlinlogging/slf4j/internal/LocationIgnorantKLogger.kt
payload entries should be added to slf4j builder so implementations like logback can make use of this data
> Append entries of payload to LoggingEventBuilder

- src/javaMain/kotlin/io/github/oshai/kotlinlogging/slf4j/Slf4jExtensions.kt
- src/javaMain/kotlin/io/github/oshai/kotlinlogging/slf4j/internal/LocationAwareKLogger.kt
- src/javaMain/kotlin/io/github/oshai/kotlinlogging/slf4j/internal/LocationIgnorantKLogger.kt
- src/javaMain/kotlin/io/github/oshai/kotlinlogging/slf4j/internal/Slf4jLogger.kt
This allows to be more backward compatible for version that doesn't support fluent logging / payload etc'
> Split cases to with / without payload.

- build.gradle.kts
- gradle.properties
- src/darwinMain/kotlin/io/github/oshai/kotlinlogging/DarwinKLogger.kt
- src/darwinMain/kotlin/io/github/oshai/kotlinlogging/KotlinLoggingConfiguration.kt
- src/darwinMain/kotlin/io/github/oshai/kotlinlogging/internal/KLoggerFactory.kt
- src/nativeMain/kotlin/io/github/oshai/kotlinlogging/ConsoleOutputAppender.kt
- src/nativeMain/kotlin/io/github/oshai/kotlinlogging/KotlinLoggingConfiguration.kt
Should fix issues in #373 automatic PR
> Update Kotlin to 1.9.21

- .github/workflows/github-pages.yml
Fixes #382
Demo: https://edricchan03.github.io/kotlin-logging/api/ ([workflow run](https://github.com/EdricChan03/kotlin-logging/actions/runs/7302473812))
Note: You'll have to change the GitHub Pages source to use GitHub Actions instead, see the [help docs on configuring a publishing source](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow) for more info
I've also noticed that there's a really old "docs" folder that doesn't seem to be used - should this be removed as well?
(Also, let me know if I should squash the 8 commits together on my end)
> Add workflow to publish Dokka HTML docs to project site

- build.gradle.kts
- src/wasmJsMain/kotlin/io/github/oshai/kotlinlogging/ConsoleOutputAppender.kt
- src/wasmJsMain/kotlin/io/github/oshai/kotlinlogging/KotlinLoggingConfiguration.kt
- src/wasmJsMain/kotlin/io/github/oshai/kotlinlogging/internal/KLoggerNameResolver.kt
- src/wasmJsTest/kotlin/io/github/oshai/kotlinlogging/ConsoleOutputAppenderTest.kt
- src/wasmJsTest/kotlin/io/github/oshai/kotlinlogging/SimpleWasmJsTest.kt
Partially solves #306.
No Node.js support for now, as it requires a canary Node.js version ([21.0.0-v8-canary202309143a48826a08 or newer](https://youtrack.jetbrains.com/issue/KT-63014/Running-tests-with-wasmJs-in-1.9.20-requires-Chrome-Canary#focus=Comments-27-8321383.0-0)).
No WASI support also. Considering the raw state of Kotlin WASI, this currently seems too hard to implement.
Overall, this is a fairly simple implementation based on the `jsMain` and `jsTest` modules. I hope this will be ok as a first solution, just to provide initial support for WASM.
> Add Kotlin/Wasm (JS browser) support

- src/darwinMain/kotlin/io/github/oshai/kotlinlogging/DarwinKLogger.kt
> Log marker and stacktrace on Darwin

- src/commonMain/kotlin/io/github/oshai/kotlinlogging/KLogger.kt
- src/commonTest/kotlin/io/github/oshai/kotlinlogging/SimpleTest.kt
I think the api could be improved a bit by not requiring the throwable, which could result in the following:
```
logger.info(marker=myMarker) { "some Message" }
```
Especially you do not need to supply a throwable when logging info in this case.
Due to the deprecation of the previous methods the test still uses deprecated methods. 
If the old methods are removed, the problem wont occur anymore.
> allow only markers being supplied

- src/javaMain/kotlin/io/github/oshai/kotlinlogging/slf4j/Slf4jExtensions.kt
- src/javaMain/kotlin/io/github/oshai/kotlinlogging/slf4j/internal/Slf4jMarker.kt
- src/jvmTest/kotlin/io/github/oshai/kotlinlogging/slf4j/Slf4jMarkerTest.kt
This fixes #360.
~~`./gradlew spotlessCheck` fails on this PR because of the ancient version of ktfmt used in the project (0.24).~~
> Allow supplying org.slf4j.Marker

- .gitattributes
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/github-pages.yml
- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- src/commonTest/kotlin/io/github/oshai/kotlinlogging/SimpleTest.kt
- src/jsTest/kotlin/io/github/oshai/kotlinlogging/SimpleJsTest.kt
- versions.gradle.kts
Upgraded Gradle to 8.7; Upgraded Android plugin to 8.2.2; Upgraded Kotlin Coroutines version to 1.8.0; Enabled cross-platform compatibility for Spotless plugin; Silencing some compiler warnings
Fixes #288
> Upgrading Gradle to 8.X

- src/wasmJsMain/kotlin/io/github/oshai/kotlinlogging/internal/KLoggerNameResolver.kt
- src/wasmJsTest/kotlin/io/github/oshai/kotlinlogging/SimpleWasmJsTest.kt
Refined algorithm to determine the name of the hosting class of an anonymous logger
> WASM Anonymous Logging Refinement

- src/directMain/kotlin/io/github/oshai/kotlinlogging/Formatter.kt
- src/jsTest/kotlin/io/github/oshai/kotlinlogging/SimpleJsTest.kt
This simplifies the code a bit and will allow tailrec optimization in native builds
> Leverage tail recursion when creating message out of Throwable

- src/javaMain/kotlin/io/github/oshai/kotlinlogging/internal/KLoggerNameResolver.kt
- src/jvmTest/kotlin/io/github/oshai/kotlinlogging/internal/KLoggerNameResolverTest.kt
> Issue #484 - Optimize the KLoggerNameResolver for jvm

- .github/workflows/github-pages.yml
- build.gradle.kts
- gradle.properties
there are instructions here: https://kotlinlang.org/docs/dokka-migration.html
> upgrade dokka to v2
